apiVersion: v1
kind: Pod
metadata:
  name: xpu-pod-3
spec:
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  containers:
    - name: xpu-container-3-0
      image: ubuntu:16.04
      command:
        - /bin/sleep
        - 10h
      resources:
        limits:
          baidu.com/xpu: 1 # requesting 1 GPUs
    - name: xpu-container-3-1
      image: ubuntu:16.04
      command:
        - /bin/sleep
        - 10h
      resources:
        limits:
          baidu.com/xpu: 1 # requesting 1 GPUs
    - name: xpu-container-3-2
      image: ubuntu:16.04
      command:
        - /bin/sleep
        - 10h
      resources:
        limits:
          baidu.com/xpu: 1 # requesting 1 GPUs
